project:
  type: website
  output-dir: docs 

website:
  title: "website06"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - href: QuickStart.qmd
        text: "Start"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

